/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraHerramientas = new javax.swing.JToolBar();
        btnDepartamento = new javax.swing.JButton();
        btnPuesto = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnJornada = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuDepartamentos = new javax.swing.JMenuItem();
        mnuPuestos = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuJornadas = new javax.swing.JMenuItem();
        mnuPlanillas = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuVentanaMain = new javax.swing.JMenu();
        mnuMaximizar = new javax.swing.JMenuItem();
        mnuVentana = new javax.swing.JMenuItem();
        mnuMinimizar = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();
        mnuContenido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDepartamento.setText("Departamento");
        btnDepartamento.setFocusable(false);
        btnDepartamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDepartamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentoActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnDepartamento);

        btnPuesto.setText("Puesto");
        btnPuesto.setFocusable(false);
        btnPuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestoActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnPuesto);

        btnEmpleado.setText("Empleado");
        btnEmpleado.setFocusable(false);
        btnEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnEmpleado);

        btnJornada.setText("Jornada");
        btnJornada.setFocusable(false);
        btnJornada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJornada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJornadaActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnJornada);

        btnExit.setText("Salir");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnExit);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuDepartamentos.setText("Departamentos");
        mnuArchivo.add(mnuDepartamentos);

        mnuPuestos.setText("Puestos de trabajo");
        mnuArchivo.add(mnuPuestos);

        mnuEmpleados.setText("Empleados");
        mnuArchivo.add(mnuEmpleados);

        mnuJornadas.setText("Jornadas Laborales");
        mnuArchivo.add(mnuJornadas);

        mnuPlanillas.setText("Planillas");
        mnuArchivo.add(mnuPlanillas);

        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuUsuario);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuVentanaMain.setText("Ventana");

        mnuMaximizar.setText("Maximizar");
        mnuMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMaximizarActionPerformed(evt);
            }
        });
        mnuVentanaMain.add(mnuMaximizar);

        mnuVentana.setText("Ventana");
        mnuVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentanaActionPerformed(evt);
            }
        });
        mnuVentanaMain.add(mnuVentana);

        mnuMinimizar.setText("Minimizar");
        mnuMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMinimizarActionPerformed(evt);
            }
        });
        mnuVentanaMain.add(mnuMinimizar);

        jMenuBar1.add(mnuVentanaMain);

        mnuAyuda.setText("Ayuda");

        mnuAcercaDe.setText("Acerca de...");
        mnuAyuda.add(mnuAcercaDe);

        mnuContenido.setText("Contenido");
        mnuAyuda.add(mnuContenido);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMaximizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_mnuMaximizarActionPerformed

    private void mnuVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentanaActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(NORMAL);
    }//GEN-LAST:event_mnuVentanaActionPerformed

    private void mnuMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_mnuMinimizarActionPerformed

    private void btnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentoActionPerformed
    MostrarDepartamento verDepartamentos = new MostrarDepartamento();
    escritorio.add(verDepartamentos);
    verDepartamentos.show();
    }//GEN-LAST:event_btnDepartamentoActionPerformed

    private void btnPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestoActionPerformed
    MostrarPuestoTrabajo verPuestoTrabajo = new MostrarPuestoTrabajo();
    escritorio.add(verPuestoTrabajo);
    verPuestoTrabajo.show();
    }//GEN-LAST:event_btnPuestoActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
    MostrarEmpleado verEmpleados = new MostrarEmpleado();
    escritorio.add(verEmpleados);
    verEmpleados.show();
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int opcion;
        opcion= JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJornadaActionPerformed
    MostrarJornadaLaboral verJornadaLaboral = new MostrarJornadaLaboral();
    escritorio.add(verJornadaLaboral);
    verJornadaLaboral.show();
    }//GEN-LAST:event_btnJornadaActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        int opcion;
        opcion= JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        UserForm mostrarUsuario = new UserForm();
        mostrarUsuario.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.put("control", new Color(255,255,255));
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJornada;
    private javax.swing.JButton btnPuesto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuContenido;
    private javax.swing.JMenuItem mnuDepartamentos;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuJornadas;
    private javax.swing.JMenuItem mnuMaximizar;
    private javax.swing.JMenuItem mnuMinimizar;
    private javax.swing.JMenuItem mnuPlanillas;
    private javax.swing.JMenuItem mnuPuestos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JMenuItem mnuVentana;
    private javax.swing.JMenu mnuVentanaMain;
    // End of variables declaration//GEN-END:variables
}
